# Generated by Django 5.1 on 2024-08-15 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
